# Generated by Django 3.2.9 on 2021-11-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_barber'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.barber'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
