# Generated by Django 3.2.9 on 2021-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='treatment',
        ),
    ]
