# Generated by Django 3.2.9 on 2021-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_availability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
