# Generated by Django 3.2.9 on 2021-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_availability_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
