# Generated by Django 3.2.9 on 2021-11-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_treatment_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
