# Generated by Django 3.2.9 on 2021-11-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_barber'),
        ('booking', '0008_auto_20211124_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.barber'),
        ),
        migrations.DeleteModel(
            name='Barber',
        ),
    ]
